server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_goods?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mall-goods-service

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.springframework: INFO
    com.moon.mall: DEBUG
  file:
    path: /home/log

mybatis:
  type-aliases-package: com.moon.mall.goods
  mapper-locations: classpath:mapper/*Dao.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
