server:
  port: 8084
spring:
  application:
    name: mall-search
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200


logging:
  level:
    org.springframework: INFO
    com.moon.mall: DEBUG
  file:
    path: /home/log/serach